"""
Django settings for dev_server project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ea^lt1(6-p$rrn&g7nfrse83orr2nx90_upx%6)3u!@fb0y97k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # na czas developmentu – możesz później ograniczyć

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    #'django.contrib.staticfiles', wyłączamy aby funkcja smart_static() z urls.py się wykonała
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dev_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dev_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/'                                       # wszystkie ścieżki od roota
STATICFILES_DIRS = [
    BASE_DIR / "upload" / "web",                       # ← dokładnie Software/upload/web
]


MEDIA_URL = None   # jest konflikt bo domyślnie jest w '/' - tam gdzie wstawiamy STATIC_URL

# Wyciszamy ostrzeżenia o migracjach (nie potrzebujemy bazy)
SILENCED_SYSTEM_CHECKS = ["staticfiles.W004", "admin.E408"]


# # WYŁĄCZAMY CAŁKOWICIE CACHE DLA DEWELOPERA
# if DEBUG:
#     # Tworzymy własny middleware, który dodaje nagłówki no-cache do każdej odpowiedzi
#     class DisableCacheMiddleware:
#         def __init__(self, get_response):
#             self.get_response = get_response

#         def __call__(self, request):
#             response = self.get_response(request)
#             # Te nagłówki zabijają cache przeglądarki i Django
#             response['Cache-Control'] = 'no-cache, no-store, must-revalidate, max-age=0'
#             response['Pragma'] = 'no-cache'
#             response['Expires'] = '-1'
#             return response

#     # Dodajemy nasz middleware NA SAMYM POCZĄTKU listy (ważne!)
#     MIDDLEWARE = ['dev_server.settings.DisableCacheMiddleware'] + MIDDLEWARE